version: '3.4'

services:
  ruian-api:
    build: .
    ports:
     - "4569:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ruian
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healtz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
  postgres:
    image: postgis/postgis:11-3.0
    environment:
      POSTGRES_DB: ruian
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./import:/import
      - ./sql:/sql
